GET http://localhost:3001/todos/?status=TO20%DO
###

GET http://localhost:3001/todos/?priority=HIGH
###

GET http://localhost:3001/todos/?priority=HIGH&status=IN%20PROGRESS
###

GET http://localhost:3001/todos/?search_q=Play